# Imagen base ligera de Python
FROM python:3.12-slim

# Directorio de trabajo dentro del contenedor
WORKDIR /app

# Instalacion de dependencias de sistema necesarios para drivers de postgresql
RUN apt-get update && apt-get install -y \
    libpq-dev \
    gcc \
    && rm -rf /var/lib/apt/lists/*

# Copiamos solo requirements primero para aprovechar la cache de capas de docker
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiamos el resto del codigo
COPY . .

# Comando de inicio con Uvicorn (servidor ASGI de alto rendimiento)
#  --reload permite que los cambios en el codigo se reflejen sin reiniciar el contenedor
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
